services:
  backend:
    image: node:20.14.0
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=library
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      #- db-data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  migrate-and-seed:
    image: node:20.14.0
    working_dir: /app
    volumes:
      - ./db:/app
    command: bash -c "npm install && npm run migrate && npm run seed"
    depends_on:
      - db

volumes:
  db-data:
