services:
  backend:
    image: node:20.14.0
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=library
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      #- db-data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  # pgadmin:
  #   image: dpage/pgadmin4:8.8
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root@pgadmin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 15432:80
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - db

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - db:db
    environment:
      - PGWEB_DATABASE_URL=postgres://root:root@db:5432/library?sslmode=disable
    depends_on:
      - db

  migrate-and-seed:
    image: node:20.14.0
    working_dir: /app
    volumes:
      - ./db:/app
    command: bash -c "npm install && npm run migrate && npm run seed"
    depends_on:
      - db

volumes:
  db-data:
  pgadmin:
